language: cpp

os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make -C make
  - make -C make test
  - make -C make gcov
branches:
  only:
    - master
after_success:
    - bash <(curl -s https://codecov.io/bash)
